name: hf_challenge
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - blas=1.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.1
  - cpython=3.10.18
  - cycler=0.11.0
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.1
  - fonttools=4.55.3
  - freeglut=3.4.0
  - freetype=2.13.3
  - icc_rt=2022.1.0
  - icu=73.1
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lcms2=2.16
  - lerc=4.0.0
  - libdeflate=1.22
  - libffi=3.4.4
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.18
  - libtiff=4.7.0
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.2
  - openssl=3.5.0
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2024.1
  - pywin32=307
  - pyzmq=26.2.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - scikit-learn=1.6.1
  - scipy=1.15.3
  - seaborn=0.13.2
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tomli=2.0.1
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=15.1.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - autograd==1.8.0
      - autograd-gamma==0.5.0
      - formulaic==1.1.1
      - interface-meta==1.3.0
      - lifelines==0.30.0
      - wrapt==1.17.2
      - xgboost==3.0.2
prefix: C:\Users\matteucc\AppData\Local\anaconda3\envs\hf_challenge
